name: simple_routes
description: Simple, declarative route and navigation management for go_router.
version: 2.0.4
homepage: https://github.com/andyhorn/simple_routes
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ">=12.0.0 <17.0.0"
  simple_routes_annotations: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.1

topics:
  - go-router
  - navigation
  - routing
