name: simple_routes_workspace
description: The melos workspace for the simple_routes package.
repository: https://github.com/andyhorn/simple_routes.git

workspace:
  - packages/simple_routes
  - packages/simple_routes_annotations
  - packages/simple_routes_generator
  - packages/simple_routes/example

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  melos: ^7.3.0

melos:
  packages:
    - packages/simple_routes
    - packages/simple_routes_annotations
    - packages/simple_routes_generator
    - packages/simple_routes/example

  scripts:
    test:
      name: Test
      description: Run tests for all packages
      steps:
        - melos exec -c 1 --flutter -- flutter test
        - melos exec -c 1 --no-flutter -- dart test
    analyze:
      name: Analyze
      description: Analyze all packages
      steps:
        - melos exec -c 1 --flutter -- flutter analyze
        - melos exec -c 1 --no-flutter -- dart analyze
    format:
      name: Format
      description: Format all packages
      exec: dart format .
