name: example
description: A new Flutter project.
publish_to: "none" 
version: 2.0.1
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  go_router: ^17.0.0
  simple_routes: any

dev_dependencies:
  build_runner: ^2.10.5

  flutter_test:
    sdk: flutter

  simple_routes_generator: any
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
