name: simple_routes_generator
description: Code generator for the simple_routes package.
version: 0.0.1
homepage: https://github.com/andyhorn/simple_routes
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  source_gen: ^1.5.0
  simple_routes_annotations: any

dev_dependencies:
  build_runner: ^2.4.8
  build_test: ^2.2.2
  test: ^1.25.2
