name: simple_routes_generator
description: Code generator for the simple_routes package.
version: 1.0.0+beta.2
homepage: https://github.com/andyhorn/simple_routes
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  analyzer: ^8.4.1
  build: ^4.0.4
  build_config: ^1.2.0
  code_builder: ^4.10.0
  dart_style: ^3.1.3
  source_gen: ^4.1.2
  simple_routes_annotations: ^1.0.0

dev_dependencies:
  build_runner: ^2.10.5
  build_test: ^3.5.5
  test: ^1.25.2
