name: simple_routes_annotations
description: Annotations for the simple_routes package.
version: 1.0.0+beta.1
homepage: https://github.com/andyhorn/simple_routes
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta: ^1.11.0
