name: simple_routes_annotations
description: Annotations for the simple_routes package.
version: 0.0.1
homepage: https://github.com/andyhorn/simple_routes

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  meta: ^1.11.0
